// Remove the generated output, so the next build starts from nothing.
//
// `build-edge.mjs` overwrites `units/edge/public` rather than clearing it, for
// a good Windows reason it states there: the asset directories are routinely
// held open by a watcher and `rmdir` fails with EBUSY, which has nothing to do
// with the build. Its comment points at `pnpm clean` as the way to reclaim the
// leftovers. That script did not exist.
//
// It started mattering when the upstream pins moved from 0.1.0-rc.6 to rc.8:
// the frontend's filenames are content-hashed, so a new SPA does not replace
// the old one, it lands beside it. `index.html` references the new hashes and
// the old files are unreferenced — but unreferenced is not un-deployed, and
// `wrangler deploy` uploads the whole directory. Two SPAs went up where one was
// wanted.
//
//   npm run clean && npm run build:edge
//
// Everything removed here is regenerated by `build:edge` and `m0:bundle`.
// Nothing hand-written lives in these directories.
import { rmSync, existsSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const TARGETS = [
  // The compiled SPA plus the staged browser plugins. `examples/` and the three
  // loose files (index.html, favicon.svg, manifest.webmanifest) come back from
  // the frontend package and the repo's own examples/ on the next build.
  'units/edge/public',
  // Bundler output.
  'units/edge/build',
  'units/session-do/build',
]

// Empty each directory rather than remove it.
//
// Removing it is what fails. `rmSync` on `units/edge/public` raised the exact
// EBUSY on `rmdir` that build-edge's comment predicts, with five retries and
// nothing obviously holding it — an asset server that has exited, an indexer, a
// shell whose cwd is inside. The contents delete fine; it is the final rmdir on
// the directory itself that a handle blocks. Leaving the directory in place is
// also what the next build wants, so there was never a reason to remove it.
for (const target of TARGETS) {
  if (!existsSync(target)) { console.log(`  (absent) ${target}`); continue }
  let removed = 0
  for (const entry of readdirSync(target)) {
    // maxRetries covers the transient case one level down, where a watcher
    // holding one asset directory open usually lets go within a few hundred
    // milliseconds and failing the whole clean over it would send people to
    // delete things by hand.
    rmSync(join(target, entry), { recursive: true, force: true, maxRetries: 5, retryDelay: 200 })
    removed++
  }
  console.log(`  emptied  ${target}  (${removed} entries)`)
}

console.log('\nclean. `npm run build:edge` and `npm run m0:bundle` regenerate all of it.')
